// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/app.dart';
import 'api/simple.dart';
import 'api/single_instance_stream.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<void> dco_decode_StreamSink_unit_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthState dco_decode_auth_state(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DeviceSnapshot dco_decode_device_snapshot(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  InboxPreview dco_decode_inbox_preview(dynamic raw);

  @protected
  List<InboxPreview> dco_decode_list_inbox_preview(dynamic raw);

  @protected
  List<PeerDevice> dco_decode_list_peer_device(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RememberedDevice> dco_decode_list_remembered_device(dynamic raw);

  @protected
  List<TransferPreview> dco_decode_list_transfer_preview(dynamic raw);

  @protected
  PeerDevice dco_decode_peer_device(dynamic raw);

  @protected
  ProtocolNames dco_decode_protocol_names(dynamic raw);

  @protected
  RememberedDevice dco_decode_remembered_device(dynamic raw);

  @protected
  ShellSnapshot dco_decode_shell_snapshot(dynamic raw);

  @protected
  TransferDirection dco_decode_transfer_direction(dynamic raw);

  @protected
  TransferPreview dco_decode_transfer_preview(dynamic raw);

  @protected
  TransferStage dco_decode_transfer_stage(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<void> sse_decode_StreamSink_unit_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthState sse_decode_auth_state(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DeviceSnapshot sse_decode_device_snapshot(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  InboxPreview sse_decode_inbox_preview(SseDeserializer deserializer);

  @protected
  List<InboxPreview> sse_decode_list_inbox_preview(
    SseDeserializer deserializer,
  );

  @protected
  List<PeerDevice> sse_decode_list_peer_device(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RememberedDevice> sse_decode_list_remembered_device(
    SseDeserializer deserializer,
  );

  @protected
  List<TransferPreview> sse_decode_list_transfer_preview(
    SseDeserializer deserializer,
  );

  @protected
  PeerDevice sse_decode_peer_device(SseDeserializer deserializer);

  @protected
  ProtocolNames sse_decode_protocol_names(SseDeserializer deserializer);

  @protected
  RememberedDevice sse_decode_remembered_device(SseDeserializer deserializer);

  @protected
  ShellSnapshot sse_decode_shell_snapshot(SseDeserializer deserializer);

  @protected
  TransferDirection sse_decode_transfer_direction(SseDeserializer deserializer);

  @protected
  TransferPreview sse_decode_transfer_preview(SseDeserializer deserializer);

  @protected
  TransferStage sse_decode_transfer_stage(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_unit_Sse(
    RustStreamSink<void> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_auth_state(AuthState self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_device_snapshot(
    DeviceSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_inbox_preview(InboxPreview self, SseSerializer serializer);

  @protected
  void sse_encode_list_inbox_preview(
    List<InboxPreview> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_peer_device(
    List<PeerDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_remembered_device(
    List<RememberedDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transfer_preview(
    List<TransferPreview> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_device(PeerDevice self, SseSerializer serializer);

  @protected
  void sse_encode_protocol_names(ProtocolNames self, SseSerializer serializer);

  @protected
  void sse_encode_remembered_device(
    RememberedDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shell_snapshot(ShellSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_transfer_direction(
    TransferDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_preview(
    TransferPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_stage(TransferStage self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
