// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/app.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1152532709;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_quarkdrop',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  bool crateApiAppAutoReceiveEnabled();

  void crateApiAppBindCloudDevice({required String deviceId});

  int crateApiAppClearCompletedTransfers();

  void crateApiAppClearCookieSession();

  void crateApiAppClearPreferredDownloadDir();

  void crateApiSimpleConfigureApp({required String configDir});

  Future<void> crateApiAppDeleteTransfer({required String jobId});

  Future<void> crateApiSimpleInitApp();

  bool crateApiAppNavigateAfterTransfer();

  int crateApiAppPollIntervalSeconds();

  String crateApiAppPreferredDownloadDir();

  String crateApiAppQuarkLoginUrl();

  Future<String> crateApiAppReceiveJob({
    required String jobFolderId,
    required String outputDir,
  });

  List<RememberedDevice> crateApiAppRememberedDevices();

  String crateApiAppRestoreRememberedDevice({required String deviceId});

  Future<String> crateApiAppResumeTask({required String jobId});

  bool crateApiAppSaveCookieString({required String cookie});

  String crateApiAppSaveDeviceName({required String name});

  String crateApiAppSavePreferredDownloadDir({required String path});

  bool crateApiAppSaveWebviewCookieString({required String cookie});

  Future<String> crateApiAppSendLocalPath({
    required String peerMailboxFolderId,
    required String peerDeviceId,
    required String peerLabel,
    required String sourcePath,
  });

  bool crateApiAppSetAutoReceiveEnabled({required bool enabled});

  bool crateApiAppSetNavigateAfterTransfer({required bool enabled});

  int crateApiAppSetPollIntervalSeconds({required int seconds});

  Future<ShellSnapshot> crateApiAppShellSnapshot();

  Future<void> crateApiAppSignOut({required bool deleteRemoteMailbox});

  bool crateApiAppValidateCookieString({required String cookie});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiAppAutoReceiveEnabled() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppAutoReceiveEnabledConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppAutoReceiveEnabledConstMeta =>
      const TaskConstMeta(debugName: "auto_receive_enabled", argNames: []);

  @override
  void crateApiAppBindCloudDevice({required String deviceId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppBindCloudDeviceConstMeta,
        argValues: [deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppBindCloudDeviceConstMeta => const TaskConstMeta(
    debugName: "bind_cloud_device",
    argNames: ["deviceId"],
  );

  @override
  int crateApiAppClearCompletedTransfers() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppClearCompletedTransfersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppClearCompletedTransfersConstMeta =>
      const TaskConstMeta(debugName: "clear_completed_transfers", argNames: []);

  @override
  void crateApiAppClearCookieSession() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppClearCookieSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppClearCookieSessionConstMeta =>
      const TaskConstMeta(debugName: "clear_cookie_session", argNames: []);

  @override
  void crateApiAppClearPreferredDownloadDir() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppClearPreferredDownloadDirConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppClearPreferredDownloadDirConstMeta =>
      const TaskConstMeta(
        debugName: "clear_preferred_download_dir",
        argNames: [],
      );

  @override
  void crateApiSimpleConfigureApp({required String configDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleConfigureAppConstMeta,
        argValues: [configDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleConfigureAppConstMeta =>
      const TaskConstMeta(debugName: "configure_app", argNames: ["configDir"]);

  @override
  Future<void> crateApiAppDeleteTransfer({required String jobId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jobId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppDeleteTransferConstMeta,
        argValues: [jobId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppDeleteTransferConstMeta =>
      const TaskConstMeta(debugName: "delete_transfer", argNames: ["jobId"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiAppNavigateAfterTransfer() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppNavigateAfterTransferConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppNavigateAfterTransferConstMeta =>
      const TaskConstMeta(debugName: "navigate_after_transfer", argNames: []);

  @override
  int crateApiAppPollIntervalSeconds() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppPollIntervalSecondsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppPollIntervalSecondsConstMeta =>
      const TaskConstMeta(debugName: "poll_interval_seconds", argNames: []);

  @override
  String crateApiAppPreferredDownloadDir() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppPreferredDownloadDirConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppPreferredDownloadDirConstMeta =>
      const TaskConstMeta(debugName: "preferred_download_dir", argNames: []);

  @override
  String crateApiAppQuarkLoginUrl() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppQuarkLoginUrlConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppQuarkLoginUrlConstMeta =>
      const TaskConstMeta(debugName: "quark_login_url", argNames: []);

  @override
  Future<String> crateApiAppReceiveJob({
    required String jobFolderId,
    required String outputDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jobFolderId, serializer);
          sse_encode_String(outputDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppReceiveJobConstMeta,
        argValues: [jobFolderId, outputDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppReceiveJobConstMeta => const TaskConstMeta(
    debugName: "receive_job",
    argNames: ["jobFolderId", "outputDir"],
  );

  @override
  List<RememberedDevice> crateApiAppRememberedDevices() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_remembered_device,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppRememberedDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppRememberedDevicesConstMeta =>
      const TaskConstMeta(debugName: "remembered_devices", argNames: []);

  @override
  String crateApiAppRestoreRememberedDevice({required String deviceId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppRestoreRememberedDeviceConstMeta,
        argValues: [deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppRestoreRememberedDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "restore_remembered_device",
        argNames: ["deviceId"],
      );

  @override
  Future<String> crateApiAppResumeTask({required String jobId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jobId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppResumeTaskConstMeta,
        argValues: [jobId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppResumeTaskConstMeta =>
      const TaskConstMeta(debugName: "resume_task", argNames: ["jobId"]);

  @override
  bool crateApiAppSaveCookieString({required String cookie}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cookie, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppSaveCookieStringConstMeta,
        argValues: [cookie],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppSaveCookieStringConstMeta =>
      const TaskConstMeta(
        debugName: "save_cookie_string",
        argNames: ["cookie"],
      );

  @override
  String crateApiAppSaveDeviceName({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppSaveDeviceNameConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppSaveDeviceNameConstMeta =>
      const TaskConstMeta(debugName: "save_device_name", argNames: ["name"]);

  @override
  String crateApiAppSavePreferredDownloadDir({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppSavePreferredDownloadDirConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppSavePreferredDownloadDirConstMeta =>
      const TaskConstMeta(
        debugName: "save_preferred_download_dir",
        argNames: ["path"],
      );

  @override
  bool crateApiAppSaveWebviewCookieString({required String cookie}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cookie, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppSaveWebviewCookieStringConstMeta,
        argValues: [cookie],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppSaveWebviewCookieStringConstMeta =>
      const TaskConstMeta(
        debugName: "save_webview_cookie_string",
        argNames: ["cookie"],
      );

  @override
  Future<String> crateApiAppSendLocalPath({
    required String peerMailboxFolderId,
    required String peerDeviceId,
    required String peerLabel,
    required String sourcePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerMailboxFolderId, serializer);
          sse_encode_String(peerDeviceId, serializer);
          sse_encode_String(peerLabel, serializer);
          sse_encode_String(sourcePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppSendLocalPathConstMeta,
        argValues: [peerMailboxFolderId, peerDeviceId, peerLabel, sourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppSendLocalPathConstMeta => const TaskConstMeta(
    debugName: "send_local_path",
    argNames: [
      "peerMailboxFolderId",
      "peerDeviceId",
      "peerLabel",
      "sourcePath",
    ],
  );

  @override
  bool crateApiAppSetAutoReceiveEnabled({required bool enabled}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppSetAutoReceiveEnabledConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppSetAutoReceiveEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "set_auto_receive_enabled",
        argNames: ["enabled"],
      );

  @override
  bool crateApiAppSetNavigateAfterTransfer({required bool enabled}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppSetNavigateAfterTransferConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppSetNavigateAfterTransferConstMeta =>
      const TaskConstMeta(
        debugName: "set_navigate_after_transfer",
        argNames: ["enabled"],
      );

  @override
  int crateApiAppSetPollIntervalSeconds({required int seconds}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(seconds, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppSetPollIntervalSecondsConstMeta,
        argValues: [seconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppSetPollIntervalSecondsConstMeta =>
      const TaskConstMeta(
        debugName: "set_poll_interval_seconds",
        argNames: ["seconds"],
      );

  @override
  Future<ShellSnapshot> crateApiAppShellSnapshot() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_shell_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppShellSnapshotConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppShellSnapshotConstMeta =>
      const TaskConstMeta(debugName: "shell_snapshot", argNames: []);

  @override
  Future<void> crateApiAppSignOut({required bool deleteRemoteMailbox}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(deleteRemoteMailbox, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppSignOutConstMeta,
        argValues: [deleteRemoteMailbox],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppSignOutConstMeta => const TaskConstMeta(
    debugName: "sign_out",
    argNames: ["deleteRemoteMailbox"],
  );

  @override
  bool crateApiAppValidateCookieString({required String cookie}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cookie, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppValidateCookieStringConstMeta,
        argValues: [cookie],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppValidateCookieStringConstMeta =>
      const TaskConstMeta(
        debugName: "validate_cookie_string",
        argNames: ["cookie"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AuthState dco_decode_auth_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AuthState.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DeviceSnapshot dco_decode_device_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return DeviceSnapshot(
      deviceId: dco_decode_String(arr[0]),
      deviceName: dco_decode_String(arr[1]),
      authSource: dco_decode_String(arr[2]),
      mailboxStatusLabel: dco_decode_String(arr[3]),
      mailboxSummary: dco_decode_String(arr[4]),
      inboxJobCount: dco_decode_i_32(arr[5]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  InboxPreview dco_decode_inbox_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return InboxPreview(
      id: dco_decode_String(arr[0]),
      sender: dco_decode_String(arr[1]),
      rootName: dco_decode_String(arr[2]),
      summary: dco_decode_String(arr[3]),
      sizeLabel: dco_decode_String(arr[4]),
      receivedAtLabel: dco_decode_String(arr[5]),
      isReady: dco_decode_bool(arr[6]),
    );
  }

  @protected
  List<InboxPreview> dco_decode_list_inbox_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_inbox_preview).toList();
  }

  @protected
  List<PeerDevice> dco_decode_list_peer_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_peer_device).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RememberedDevice> dco_decode_list_remembered_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_remembered_device).toList();
  }

  @protected
  List<TransferPreview> dco_decode_list_transfer_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_transfer_preview).toList();
  }

  @protected
  PeerDevice dco_decode_peer_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PeerDevice(
      deviceId: dco_decode_String(arr[0]),
      mailboxFolderId: dco_decode_String(arr[1]),
      label: dco_decode_String(arr[2]),
      subtitle: dco_decode_String(arr[3]),
    );
  }

  @protected
  ProtocolNames dco_decode_protocol_names(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ProtocolNames(
      manifestName: dco_decode_String(arr[0]),
      commitName: dco_decode_String(arr[1]),
    );
  }

  @protected
  RememberedDevice dco_decode_remembered_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RememberedDevice(
      deviceId: dco_decode_String(arr[0]),
      deviceName: dco_decode_String(arr[1]),
      isCurrent: dco_decode_bool(arr[2]),
    );
  }

  @protected
  ShellSnapshot dco_decode_shell_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ShellSnapshot(
      authState: dco_decode_auth_state(arr[0]),
      protocolNames: dco_decode_protocol_names(arr[1]),
      deviceSnapshot: dco_decode_device_snapshot(arr[2]),
      inboxPreviews: dco_decode_list_inbox_preview(arr[3]),
      peerDevices: dco_decode_list_peer_device(arr[4]),
      transferPreviews: dco_decode_list_transfer_preview(arr[5]),
    );
  }

  @protected
  TransferDirection dco_decode_transfer_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TransferDirection.values[raw as int];
  }

  @protected
  TransferPreview dco_decode_transfer_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TransferPreview(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      subtitle: dco_decode_String(arr[2]),
      progress: dco_decode_f_64(arr[3]),
      stage: dco_decode_transfer_stage(arr[4]),
      direction: dco_decode_transfer_direction(arr[5]),
    );
  }

  @protected
  TransferStage dco_decode_transfer_stage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TransferStage.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AuthState sse_decode_auth_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AuthState.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DeviceSnapshot sse_decode_device_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_authSource = sse_decode_String(deserializer);
    var var_mailboxStatusLabel = sse_decode_String(deserializer);
    var var_mailboxSummary = sse_decode_String(deserializer);
    var var_inboxJobCount = sse_decode_i_32(deserializer);
    return DeviceSnapshot(
      deviceId: var_deviceId,
      deviceName: var_deviceName,
      authSource: var_authSource,
      mailboxStatusLabel: var_mailboxStatusLabel,
      mailboxSummary: var_mailboxSummary,
      inboxJobCount: var_inboxJobCount,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  InboxPreview sse_decode_inbox_preview(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sender = sse_decode_String(deserializer);
    var var_rootName = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_sizeLabel = sse_decode_String(deserializer);
    var var_receivedAtLabel = sse_decode_String(deserializer);
    var var_isReady = sse_decode_bool(deserializer);
    return InboxPreview(
      id: var_id,
      sender: var_sender,
      rootName: var_rootName,
      summary: var_summary,
      sizeLabel: var_sizeLabel,
      receivedAtLabel: var_receivedAtLabel,
      isReady: var_isReady,
    );
  }

  @protected
  List<InboxPreview> sse_decode_list_inbox_preview(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InboxPreview>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_inbox_preview(deserializer));
    }
    return ans_;
  }

  @protected
  List<PeerDevice> sse_decode_list_peer_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PeerDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_peer_device(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RememberedDevice> sse_decode_list_remembered_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RememberedDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_remembered_device(deserializer));
    }
    return ans_;
  }

  @protected
  List<TransferPreview> sse_decode_list_transfer_preview(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TransferPreview>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transfer_preview(deserializer));
    }
    return ans_;
  }

  @protected
  PeerDevice sse_decode_peer_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_mailboxFolderId = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_subtitle = sse_decode_String(deserializer);
    return PeerDevice(
      deviceId: var_deviceId,
      mailboxFolderId: var_mailboxFolderId,
      label: var_label,
      subtitle: var_subtitle,
    );
  }

  @protected
  ProtocolNames sse_decode_protocol_names(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_manifestName = sse_decode_String(deserializer);
    var var_commitName = sse_decode_String(deserializer);
    return ProtocolNames(
      manifestName: var_manifestName,
      commitName: var_commitName,
    );
  }

  @protected
  RememberedDevice sse_decode_remembered_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_isCurrent = sse_decode_bool(deserializer);
    return RememberedDevice(
      deviceId: var_deviceId,
      deviceName: var_deviceName,
      isCurrent: var_isCurrent,
    );
  }

  @protected
  ShellSnapshot sse_decode_shell_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_authState = sse_decode_auth_state(deserializer);
    var var_protocolNames = sse_decode_protocol_names(deserializer);
    var var_deviceSnapshot = sse_decode_device_snapshot(deserializer);
    var var_inboxPreviews = sse_decode_list_inbox_preview(deserializer);
    var var_peerDevices = sse_decode_list_peer_device(deserializer);
    var var_transferPreviews = sse_decode_list_transfer_preview(deserializer);
    return ShellSnapshot(
      authState: var_authState,
      protocolNames: var_protocolNames,
      deviceSnapshot: var_deviceSnapshot,
      inboxPreviews: var_inboxPreviews,
      peerDevices: var_peerDevices,
      transferPreviews: var_transferPreviews,
    );
  }

  @protected
  TransferDirection sse_decode_transfer_direction(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TransferDirection.values[inner];
  }

  @protected
  TransferPreview sse_decode_transfer_preview(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_subtitle = sse_decode_String(deserializer);
    var var_progress = sse_decode_f_64(deserializer);
    var var_stage = sse_decode_transfer_stage(deserializer);
    var var_direction = sse_decode_transfer_direction(deserializer);
    return TransferPreview(
      id: var_id,
      title: var_title,
      subtitle: var_subtitle,
      progress: var_progress,
      stage: var_stage,
      direction: var_direction,
    );
  }

  @protected
  TransferStage sse_decode_transfer_stage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TransferStage.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_auth_state(AuthState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_device_snapshot(
    DeviceSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.authSource, serializer);
    sse_encode_String(self.mailboxStatusLabel, serializer);
    sse_encode_String(self.mailboxSummary, serializer);
    sse_encode_i_32(self.inboxJobCount, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_inbox_preview(InboxPreview self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.sender, serializer);
    sse_encode_String(self.rootName, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_String(self.sizeLabel, serializer);
    sse_encode_String(self.receivedAtLabel, serializer);
    sse_encode_bool(self.isReady, serializer);
  }

  @protected
  void sse_encode_list_inbox_preview(
    List<InboxPreview> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_inbox_preview(item, serializer);
    }
  }

  @protected
  void sse_encode_list_peer_device(
    List<PeerDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_peer_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_remembered_device(
    List<RememberedDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_remembered_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_transfer_preview(
    List<TransferPreview> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transfer_preview(item, serializer);
    }
  }

  @protected
  void sse_encode_peer_device(PeerDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.mailboxFolderId, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.subtitle, serializer);
  }

  @protected
  void sse_encode_protocol_names(ProtocolNames self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.manifestName, serializer);
    sse_encode_String(self.commitName, serializer);
  }

  @protected
  void sse_encode_remembered_device(
    RememberedDevice self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_bool(self.isCurrent, serializer);
  }

  @protected
  void sse_encode_shell_snapshot(ShellSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_auth_state(self.authState, serializer);
    sse_encode_protocol_names(self.protocolNames, serializer);
    sse_encode_device_snapshot(self.deviceSnapshot, serializer);
    sse_encode_list_inbox_preview(self.inboxPreviews, serializer);
    sse_encode_list_peer_device(self.peerDevices, serializer);
    sse_encode_list_transfer_preview(self.transferPreviews, serializer);
  }

  @protected
  void sse_encode_transfer_direction(
    TransferDirection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_transfer_preview(
    TransferPreview self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.subtitle, serializer);
    sse_encode_f_64(self.progress, serializer);
    sse_encode_transfer_stage(self.stage, serializer);
    sse_encode_transfer_direction(self.direction, serializer);
  }

  @protected
  void sse_encode_transfer_stage(TransferStage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
