// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_remote_job_ids`, `auth_source_label`, `build_cleanup_scan_result`, `classify_job_entry`, `cleanup_item_subtitle`, `cleanup_item_title`, `cleanup_updated_label`, `is_reserved_mailbox_entry`, `load_transfer_previews`, `map_task_snapshot`, `remote_entry_size_bytes`, `scan_mailbox_cleanup_items`, `size_label`, `store_validated_cookie`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `cmp`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `partial_cmp`

Future<ShellSnapshot> shellSnapshot() =>
    RustLib.instance.api.crateApiAppShellSnapshot();

String quarkLoginUrl() => RustLib.instance.api.crateApiAppQuarkLoginUrl();

bool validateCookieString({required String cookie}) =>
    RustLib.instance.api.crateApiAppValidateCookieString(cookie: cookie);

bool saveCookieString({required String cookie}) =>
    RustLib.instance.api.crateApiAppSaveCookieString(cookie: cookie);

bool saveWebviewCookieString({required String cookie}) =>
    RustLib.instance.api.crateApiAppSaveWebviewCookieString(cookie: cookie);

void clearCookieSession() =>
    RustLib.instance.api.crateApiAppClearCookieSession();

Future<void> signOut({required bool deleteRemoteMailbox}) => RustLib
    .instance
    .api
    .crateApiAppSignOut(deleteRemoteMailbox: deleteRemoteMailbox);

String saveDeviceName({required String name}) =>
    RustLib.instance.api.crateApiAppSaveDeviceName(name: name);

List<RememberedDevice> rememberedDevices() =>
    RustLib.instance.api.crateApiAppRememberedDevices();

String restoreRememberedDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiAppRestoreRememberedDevice(deviceId: deviceId);

void bindCloudDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiAppBindCloudDevice(deviceId: deviceId);

String preferredLocale() => RustLib.instance.api.crateApiAppPreferredLocale();

String themeMode() => RustLib.instance.api.crateApiAppThemeMode();

String setThemeMode({required String mode}) =>
    RustLib.instance.api.crateApiAppSetThemeMode(mode: mode);

String savePreferredLocale({required String code}) =>
    RustLib.instance.api.crateApiAppSavePreferredLocale(code: code);

void clearPreferredLocale() =>
    RustLib.instance.api.crateApiAppClearPreferredLocale();

String preferredDownloadDir() =>
    RustLib.instance.api.crateApiAppPreferredDownloadDir();

String savePreferredDownloadDir({required String path}) =>
    RustLib.instance.api.crateApiAppSavePreferredDownloadDir(path: path);

void clearPreferredDownloadDir() =>
    RustLib.instance.api.crateApiAppClearPreferredDownloadDir();

bool autoReceiveEnabled() =>
    RustLib.instance.api.crateApiAppAutoReceiveEnabled();

bool setAutoReceiveEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiAppSetAutoReceiveEnabled(enabled: enabled);

bool navigateAfterTransfer() =>
    RustLib.instance.api.crateApiAppNavigateAfterTransfer();

bool setNavigateAfterTransfer({required bool enabled}) =>
    RustLib.instance.api.crateApiAppSetNavigateAfterTransfer(enabled: enabled);

int pollIntervalSeconds() =>
    RustLib.instance.api.crateApiAppPollIntervalSeconds();

int setPollIntervalSeconds({required int seconds}) =>
    RustLib.instance.api.crateApiAppSetPollIntervalSeconds(seconds: seconds);

int maxConcurrentUploads() =>
    RustLib.instance.api.crateApiAppMaxConcurrentUploads();

int setMaxConcurrentUploads({required int count}) =>
    RustLib.instance.api.crateApiAppSetMaxConcurrentUploads(count: count);

int maxConcurrentDownloads() =>
    RustLib.instance.api.crateApiAppMaxConcurrentDownloads();

int setMaxConcurrentDownloads({required int count}) =>
    RustLib.instance.api.crateApiAppSetMaxConcurrentDownloads(count: count);

bool keepScreenOnDuringTransfer() =>
    RustLib.instance.api.crateApiAppKeepScreenOnDuringTransfer();

bool setKeepScreenOnDuringTransfer({required bool enabled}) => RustLib
    .instance
    .api
    .crateApiAppSetKeepScreenOnDuringTransfer(enabled: enabled);

bool minimizeToTray() => RustLib.instance.api.crateApiAppMinimizeToTray();

bool setMinimizeToTray({required bool enabled}) =>
    RustLib.instance.api.crateApiAppSetMinimizeToTray(enabled: enabled);

bool autoMinimizeOnStart() =>
    RustLib.instance.api.crateApiAppAutoMinimizeOnStart();

bool setAutoMinimizeOnStart({required bool enabled}) =>
    RustLib.instance.api.crateApiAppSetAutoMinimizeOnStart(enabled: enabled);

int autoMinimizeDelaySeconds() =>
    RustLib.instance.api.crateApiAppAutoMinimizeDelaySeconds();

int setAutoMinimizeDelaySeconds({required int seconds}) => RustLib.instance.api
    .crateApiAppSetAutoMinimizeDelaySeconds(seconds: seconds);

int peerDiscoveryIntervalMinutes() =>
    RustLib.instance.api.crateApiAppPeerDiscoveryIntervalMinutes();

int setPeerDiscoveryIntervalMinutes({required int minutes}) => RustLib
    .instance
    .api
    .crateApiAppSetPeerDiscoveryIntervalMinutes(minutes: minutes);

Future<void> createCloudPassword({required String password}) =>
    RustLib.instance.api.crateApiAppCreateCloudPassword(password: password);

Future<void> verifyCloudPassword({required String password}) =>
    RustLib.instance.api.crateApiAppVerifyCloudPassword(password: password);

Future<void> changeCloudPassword({
  required String oldPassword,
  required String newPassword,
}) => RustLib.instance.api.crateApiAppChangeCloudPassword(
  oldPassword: oldPassword,
  newPassword: newPassword,
);

void openDataFolder() => RustLib.instance.api.crateApiAppOpenDataFolder();

void saveAutoUnlockKey() => RustLib.instance.api.crateApiAppSaveAutoUnlockKey();

bool hasSavedKey() => RustLib.instance.api.crateApiAppHasSavedKey();

void clearSavedKey() => RustLib.instance.api.crateApiAppClearSavedKey();

Future<String> sendLocalPath({
  required String peerMailboxFolderId,
  required String peerDeviceId,
  required String peerLabel,
  required String sourcePath,
  String? sourceName,
}) => RustLib.instance.api.crateApiAppSendLocalPath(
  peerMailboxFolderId: peerMailboxFolderId,
  peerDeviceId: peerDeviceId,
  peerLabel: peerLabel,
  sourcePath: sourcePath,
  sourceName: sourceName,
);

Future<String> receiveJob({
  required String jobFolderId,
  required String outputDir,
}) => RustLib.instance.api.crateApiAppReceiveJob(
  jobFolderId: jobFolderId,
  outputDir: outputDir,
);

Future<void> rejectInboxJob({required String jobFolderId}) =>
    RustLib.instance.api.crateApiAppRejectInboxJob(jobFolderId: jobFolderId);

Future<String> resumeTask({required String jobId}) =>
    RustLib.instance.api.crateApiAppResumeTask(jobId: jobId);

int clearCompletedTransfers() =>
    RustLib.instance.api.crateApiAppClearCompletedTransfers();

Future<void> deleteTransfer({required String jobId}) =>
    RustLib.instance.api.crateApiAppDeleteTransfer(jobId: jobId);

Future<CleanupScanResult> scanPeerCleanup({
  required String deviceId,
  required String mailboxFolderId,
  required String deviceLabel,
}) => RustLib.instance.api.crateApiAppScanPeerCleanup(
  deviceId: deviceId,
  mailboxFolderId: mailboxFolderId,
  deviceLabel: deviceLabel,
);

Future<CleanupScanResult> scanGlobalCleanup() =>
    RustLib.instance.api.crateApiAppScanGlobalCleanup();

Future<int> deleteCleanupItems({required List<String> itemIds}) =>
    RustLib.instance.api.crateApiAppDeleteCleanupItems(itemIds: itemIds);

Future<void> removePeerDevice({required String peerDeviceId}) => RustLib
    .instance
    .api
    .crateApiAppRemovePeerDevice(peerDeviceId: peerDeviceId);

enum AuthState { loginRequired, needCreatePassword, needVerifyPassword, ready }

enum CleanupCategory {
  readyDownloadTask,
  incompleteUploadTask,
  brokenTask,
  otherFile,
}

class CleanupItem {
  final String id;
  final String deviceId;
  final String deviceLabel;
  final String mailboxFolderId;
  final String title;
  final String subtitle;
  final BigInt sizeBytes;
  final String sizeLabel;
  final String updatedAtLabel;
  final CleanupCategory category;
  final bool canDelete;

  const CleanupItem({
    required this.id,
    required this.deviceId,
    required this.deviceLabel,
    required this.mailboxFolderId,
    required this.title,
    required this.subtitle,
    required this.sizeBytes,
    required this.sizeLabel,
    required this.updatedAtLabel,
    required this.category,
    required this.canDelete,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      deviceId.hashCode ^
      deviceLabel.hashCode ^
      mailboxFolderId.hashCode ^
      title.hashCode ^
      subtitle.hashCode ^
      sizeBytes.hashCode ^
      sizeLabel.hashCode ^
      updatedAtLabel.hashCode ^
      category.hashCode ^
      canDelete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CleanupItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          deviceId == other.deviceId &&
          deviceLabel == other.deviceLabel &&
          mailboxFolderId == other.mailboxFolderId &&
          title == other.title &&
          subtitle == other.subtitle &&
          sizeBytes == other.sizeBytes &&
          sizeLabel == other.sizeLabel &&
          updatedAtLabel == other.updatedAtLabel &&
          category == other.category &&
          canDelete == other.canDelete;
}

class CleanupScanResult {
  final int totalCount;
  final String totalSizeLabel;
  final List<CleanupItem> items;

  const CleanupScanResult({
    required this.totalCount,
    required this.totalSizeLabel,
    required this.items,
  });

  @override
  int get hashCode =>
      totalCount.hashCode ^ totalSizeLabel.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CleanupScanResult &&
          runtimeType == other.runtimeType &&
          totalCount == other.totalCount &&
          totalSizeLabel == other.totalSizeLabel &&
          items == other.items;
}

class DeviceSnapshot {
  final String deviceId;
  final String deviceName;
  final String mailboxFolderId;
  final String authSource;
  final String mailboxStatusLabel;
  final String mailboxSummary;
  final int inboxJobCount;

  const DeviceSnapshot({
    required this.deviceId,
    required this.deviceName,
    required this.mailboxFolderId,
    required this.authSource,
    required this.mailboxStatusLabel,
    required this.mailboxSummary,
    required this.inboxJobCount,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      mailboxFolderId.hashCode ^
      authSource.hashCode ^
      mailboxStatusLabel.hashCode ^
      mailboxSummary.hashCode ^
      inboxJobCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceSnapshot &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          mailboxFolderId == other.mailboxFolderId &&
          authSource == other.authSource &&
          mailboxStatusLabel == other.mailboxStatusLabel &&
          mailboxSummary == other.mailboxSummary &&
          inboxJobCount == other.inboxJobCount;
}

class InboxPreview {
  final String id;
  final String sender;
  final String rootName;
  final String summary;
  final String sizeLabel;
  final String receivedAtLabel;
  final bool isReady;

  const InboxPreview({
    required this.id,
    required this.sender,
    required this.rootName,
    required this.summary,
    required this.sizeLabel,
    required this.receivedAtLabel,
    required this.isReady,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sender.hashCode ^
      rootName.hashCode ^
      summary.hashCode ^
      sizeLabel.hashCode ^
      receivedAtLabel.hashCode ^
      isReady.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InboxPreview &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sender == other.sender &&
          rootName == other.rootName &&
          summary == other.summary &&
          sizeLabel == other.sizeLabel &&
          receivedAtLabel == other.receivedAtLabel &&
          isReady == other.isReady;
}

class PeerDevice {
  final String deviceId;
  final String mailboxFolderId;
  final String label;
  final String subtitle;

  const PeerDevice({
    required this.deviceId,
    required this.mailboxFolderId,
    required this.label,
    required this.subtitle,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      mailboxFolderId.hashCode ^
      label.hashCode ^
      subtitle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerDevice &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          mailboxFolderId == other.mailboxFolderId &&
          label == other.label &&
          subtitle == other.subtitle;
}

class ProtocolNames {
  final String manifestName;
  final String commitName;

  const ProtocolNames({required this.manifestName, required this.commitName});

  @override
  int get hashCode => manifestName.hashCode ^ commitName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtocolNames &&
          runtimeType == other.runtimeType &&
          manifestName == other.manifestName &&
          commitName == other.commitName;
}

class RememberedDevice {
  final String deviceId;
  final String deviceName;
  final bool isCurrent;

  const RememberedDevice({
    required this.deviceId,
    required this.deviceName,
    required this.isCurrent,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ deviceName.hashCode ^ isCurrent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RememberedDevice &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          isCurrent == other.isCurrent;
}

class ShellSnapshot {
  final AuthState authState;
  final ProtocolNames protocolNames;
  final DeviceSnapshot deviceSnapshot;
  final List<InboxPreview> inboxPreviews;
  final List<PeerDevice> peerDevices;
  final List<TransferPreview> transferPreviews;

  const ShellSnapshot({
    required this.authState,
    required this.protocolNames,
    required this.deviceSnapshot,
    required this.inboxPreviews,
    required this.peerDevices,
    required this.transferPreviews,
  });

  @override
  int get hashCode =>
      authState.hashCode ^
      protocolNames.hashCode ^
      deviceSnapshot.hashCode ^
      inboxPreviews.hashCode ^
      peerDevices.hashCode ^
      transferPreviews.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShellSnapshot &&
          runtimeType == other.runtimeType &&
          authState == other.authState &&
          protocolNames == other.protocolNames &&
          deviceSnapshot == other.deviceSnapshot &&
          inboxPreviews == other.inboxPreviews &&
          peerDevices == other.peerDevices &&
          transferPreviews == other.transferPreviews;
}

enum TransferDirection { send, receive }

class TransferPreview {
  final String id;
  final String title;
  final String subtitle;
  final String sizeLabel;
  final double progress;
  final TransferStage stage;
  final TransferDirection direction;

  const TransferPreview({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.sizeLabel,
    required this.progress,
    required this.stage,
    required this.direction,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      subtitle.hashCode ^
      sizeLabel.hashCode ^
      progress.hashCode ^
      stage.hashCode ^
      direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferPreview &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          subtitle == other.subtitle &&
          sizeLabel == other.sizeLabel &&
          progress == other.progress &&
          stage == other.stage &&
          direction == other.direction;
}

enum TransferStage {
  preparing,
  uploadingBlobs,
  uploadingManifest,
  uploadingCommit,
  downloadingBlobs,
  verifying,
  cleanupRemote,
  failed,
  done,
}
