// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `auth_source_label`, `load_transfer_previews`, `map_task_snapshot`, `size_label`, `store_validated_cookie`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<ShellSnapshot> shellSnapshot() =>
    RustLib.instance.api.crateApiAppShellSnapshot();

String quarkLoginUrl() => RustLib.instance.api.crateApiAppQuarkLoginUrl();

bool validateCookieString({required String cookie}) =>
    RustLib.instance.api.crateApiAppValidateCookieString(cookie: cookie);

bool saveCookieString({required String cookie}) =>
    RustLib.instance.api.crateApiAppSaveCookieString(cookie: cookie);

bool saveWebviewCookieString({required String cookie}) =>
    RustLib.instance.api.crateApiAppSaveWebviewCookieString(cookie: cookie);

void clearCookieSession() =>
    RustLib.instance.api.crateApiAppClearCookieSession();

Future<void> signOut({required bool deleteRemoteMailbox}) => RustLib
    .instance
    .api
    .crateApiAppSignOut(deleteRemoteMailbox: deleteRemoteMailbox);

String saveDeviceName({required String name}) =>
    RustLib.instance.api.crateApiAppSaveDeviceName(name: name);

List<RememberedDevice> rememberedDevices() =>
    RustLib.instance.api.crateApiAppRememberedDevices();

String restoreRememberedDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiAppRestoreRememberedDevice(deviceId: deviceId);

void bindCloudDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiAppBindCloudDevice(deviceId: deviceId);

String preferredDownloadDir() =>
    RustLib.instance.api.crateApiAppPreferredDownloadDir();

String savePreferredDownloadDir({required String path}) =>
    RustLib.instance.api.crateApiAppSavePreferredDownloadDir(path: path);

void clearPreferredDownloadDir() =>
    RustLib.instance.api.crateApiAppClearPreferredDownloadDir();

bool autoReceiveEnabled() =>
    RustLib.instance.api.crateApiAppAutoReceiveEnabled();

bool setAutoReceiveEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiAppSetAutoReceiveEnabled(enabled: enabled);

bool navigateAfterTransfer() =>
    RustLib.instance.api.crateApiAppNavigateAfterTransfer();

bool setNavigateAfterTransfer({required bool enabled}) =>
    RustLib.instance.api.crateApiAppSetNavigateAfterTransfer(enabled: enabled);

int pollIntervalSeconds() =>
    RustLib.instance.api.crateApiAppPollIntervalSeconds();

int setPollIntervalSeconds({required int seconds}) =>
    RustLib.instance.api.crateApiAppSetPollIntervalSeconds(seconds: seconds);

Future<String> sendLocalPath({
  required String peerMailboxFolderId,
  required String peerDeviceId,
  required String peerLabel,
  required String sourcePath,
}) => RustLib.instance.api.crateApiAppSendLocalPath(
  peerMailboxFolderId: peerMailboxFolderId,
  peerDeviceId: peerDeviceId,
  peerLabel: peerLabel,
  sourcePath: sourcePath,
);

Future<String> receiveJob({
  required String jobFolderId,
  required String outputDir,
}) => RustLib.instance.api.crateApiAppReceiveJob(
  jobFolderId: jobFolderId,
  outputDir: outputDir,
);

Future<String> resumeTask({required String jobId}) =>
    RustLib.instance.api.crateApiAppResumeTask(jobId: jobId);

int clearCompletedTransfers() =>
    RustLib.instance.api.crateApiAppClearCompletedTransfers();

Future<void> deleteTransfer({required String jobId}) =>
    RustLib.instance.api.crateApiAppDeleteTransfer(jobId: jobId);

enum AuthState { loginRequired, ready }

class DeviceSnapshot {
  final String deviceId;
  final String deviceName;
  final String authSource;
  final String mailboxStatusLabel;
  final String mailboxSummary;
  final int inboxJobCount;

  const DeviceSnapshot({
    required this.deviceId,
    required this.deviceName,
    required this.authSource,
    required this.mailboxStatusLabel,
    required this.mailboxSummary,
    required this.inboxJobCount,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      authSource.hashCode ^
      mailboxStatusLabel.hashCode ^
      mailboxSummary.hashCode ^
      inboxJobCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceSnapshot &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          authSource == other.authSource &&
          mailboxStatusLabel == other.mailboxStatusLabel &&
          mailboxSummary == other.mailboxSummary &&
          inboxJobCount == other.inboxJobCount;
}

class InboxPreview {
  final String id;
  final String sender;
  final String rootName;
  final String summary;
  final String sizeLabel;
  final String receivedAtLabel;
  final bool isReady;

  const InboxPreview({
    required this.id,
    required this.sender,
    required this.rootName,
    required this.summary,
    required this.sizeLabel,
    required this.receivedAtLabel,
    required this.isReady,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sender.hashCode ^
      rootName.hashCode ^
      summary.hashCode ^
      sizeLabel.hashCode ^
      receivedAtLabel.hashCode ^
      isReady.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InboxPreview &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sender == other.sender &&
          rootName == other.rootName &&
          summary == other.summary &&
          sizeLabel == other.sizeLabel &&
          receivedAtLabel == other.receivedAtLabel &&
          isReady == other.isReady;
}

class PeerDevice {
  final String deviceId;
  final String mailboxFolderId;
  final String label;
  final String subtitle;

  const PeerDevice({
    required this.deviceId,
    required this.mailboxFolderId,
    required this.label,
    required this.subtitle,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      mailboxFolderId.hashCode ^
      label.hashCode ^
      subtitle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerDevice &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          mailboxFolderId == other.mailboxFolderId &&
          label == other.label &&
          subtitle == other.subtitle;
}

class ProtocolNames {
  final String manifestName;
  final String commitName;

  const ProtocolNames({required this.manifestName, required this.commitName});

  @override
  int get hashCode => manifestName.hashCode ^ commitName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtocolNames &&
          runtimeType == other.runtimeType &&
          manifestName == other.manifestName &&
          commitName == other.commitName;
}

class RememberedDevice {
  final String deviceId;
  final String deviceName;
  final bool isCurrent;

  const RememberedDevice({
    required this.deviceId,
    required this.deviceName,
    required this.isCurrent,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ deviceName.hashCode ^ isCurrent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RememberedDevice &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          isCurrent == other.isCurrent;
}

class ShellSnapshot {
  final AuthState authState;
  final ProtocolNames protocolNames;
  final DeviceSnapshot deviceSnapshot;
  final List<InboxPreview> inboxPreviews;
  final List<PeerDevice> peerDevices;
  final List<TransferPreview> transferPreviews;

  const ShellSnapshot({
    required this.authState,
    required this.protocolNames,
    required this.deviceSnapshot,
    required this.inboxPreviews,
    required this.peerDevices,
    required this.transferPreviews,
  });

  @override
  int get hashCode =>
      authState.hashCode ^
      protocolNames.hashCode ^
      deviceSnapshot.hashCode ^
      inboxPreviews.hashCode ^
      peerDevices.hashCode ^
      transferPreviews.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShellSnapshot &&
          runtimeType == other.runtimeType &&
          authState == other.authState &&
          protocolNames == other.protocolNames &&
          deviceSnapshot == other.deviceSnapshot &&
          inboxPreviews == other.inboxPreviews &&
          peerDevices == other.peerDevices &&
          transferPreviews == other.transferPreviews;
}

enum TransferDirection { send, receive }

class TransferPreview {
  final String id;
  final String title;
  final String subtitle;
  final double progress;
  final TransferStage stage;
  final TransferDirection direction;

  const TransferPreview({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.progress,
    required this.stage,
    required this.direction,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      subtitle.hashCode ^
      progress.hashCode ^
      stage.hashCode ^
      direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferPreview &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          subtitle == other.subtitle &&
          progress == other.progress &&
          stage == other.stage &&
          direction == other.direction;
}

enum TransferStage {
  preparing,
  uploadingBlobs,
  uploadingManifest,
  uploadingCommit,
  downloadingBlobs,
  verifying,
  cleanupRemote,
  failed,
  done,
}
